services:
  tomcat:
    container_name: tomcat
    image: tomcat:6.0
    ports:
      - 8080:8080
      - 9012:9012
    environment:
      - JAVA_OPTS=-Dcom.sun.management.jmxremote.rmi.port=9012 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9012
    labels:
      com.datadoghq.tags.service: "tomcat_service"
      com.datadoghq.tags.env: "dev"
      com.datadoghq.tags.version: "0.0.1"
      com.datadoghq.ad.check_names: '["tomcat"]'
      com.datadoghq.ad.init_configs: '[{"is_jmx": true, "collect_default_metrics": true}]'
      com.datadoghq.ad.instances: '[{"host": "%%host%%","port":"9012"}]'
    networks:
      - my_network
  dd-agent:
    container_name: dd-agent
    image: gcr.io/datadoghq/agent:latest-jmx
    environment:
      - DD_API_KEY=
      - DD_SITE=ap1.datadoghq.com
      # - DD_LOG_LEVEL=info
    volumes:
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
